---
# yamllint disable rule:indentation
site_name: Terraform by example
nav:
  - Home: index.md
  - Terraform 101:
      - Lesson 1: lesson1.md
      - Lesson 2: lesson2.md
      - Lesson 3: lesson3.md
      - Lesson 4: lesson4.md
      - Lesson 5: lesson5.md
      - Lesson 6: lesson6.md
      - Lesson 7: lesson7.md
  - Terraform 201:
      - Lesson 8: lesson8.md
  - Help: help.md
  - About: about.md
theme:
  name: material
  favicon: "assets/images/favicon.ico"
repo_name: "jamesWoolfenden/terraform-by-example"
repo_url: "https://github.com/jamesWoolfenden/terraform-by-example"
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# plugins
plugins:
  - search
  - minify:
      minify_html: true
  - mkdocs-add-teaser:
      teaser_class: "teaser"
# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - type: "github"
      link: "https://github.com/slalom-consulting-ltd"
    - type: "twitter"
      link: "https://twitter.com/slalom"
    - type: "linkedin"
      link: "https://linkedin.com/company/slalom-consulting/"

# Copyright
copyright: "Copyright &copy; 2020 Slalom, LLC"
site_author: "James Woolfenden"
